server:
  port: 9002

spring:
  application:
    name: CARD-SERVICE
  data:
    mongodb:
      port: 27017
      host: localhost
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost